<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$merchant = new Merchant();
	
	$id = decode($request->id);
	$merchant->populate($id);
	$store = $merchant->getStore();
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$merchant->processPost($session->getVar(FORM_VALUES));		
	}
	
	$button_title = $this->translate("profile_button_save");
	$posturl = $this->baseUrl("merchant/edit"); 
	
	if(isEmptyString($request->tab)) {
		$request->setParam('tab', 'store');
	}
	
	$title = 'Update Store';
	if(!isMerchant()){
		$title = "Update Merchant: ".$merchant->getName();
	}
	$this->headTitle($title);
	
?>

<script>
$(document).ready(function() {
	$("#profileform-store").validate({	
		// define the validation rules one field at a time
		rules: {
			firstname: "required",
			lastname: "required",
			orgname: "required",
			contactperson: "required",		
			email: {
				required: true, 
				email: true
			},
			phone: {
				required: true, 					
				validnumber: true,
				maxlength: 10,
				minlength: 10,
				validate_ug: true
			},
			categoryid: "required",
			storename: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {		
			firstname: "<?php echo $this->translate("merchant_firstname_error"); ?>",
			lastname: "<?php echo $this->translate("merchant_lastname_error"); ?>",
			orgname: "<?php echo $this->translate("merchant_company_error"); ?>",
			contactperson: "<?php echo $this->translate("merchant_contact_error"); ?>",		
			email: {
				"required": "<?php echo $this->translate("profile_email_error"); ?>", 
				"email": "<?php echo $this->translate("profile_email_invalid_error"); ?>"
			},
			phone: {
				required: "<?php echo $this->translate("profile_phonenumber_error"); ?>", 					
				maxlength: "Phone Number must have 10 Digits",
				minlength: "Phone Number must have 10 Digits",
				validate_ug: "<?php echo $this->translate("globale_phonenumber_format"); ?>"
			},
			categoryid: "<?php echo $this->translate("merchant_category_error"); ?>",
			storename: "<?php echo $this->translate("merchant_storename_error"); ?>"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					error.appendTo("#"+element.attr("name")+"_error")
					break;
			}			
		}
	});
	
	// add the validation for wholesale price to be less than retail price
	$.validator.addMethod("validnumber", function(value, element, params) { 
		if (IsValidAmount(value)) {
			return true; 
		}
		return false;        
	}, "Please enter a valid Phone Number");
	$.validator.addMethod("validate_ug", function(value, element, params) { 
		if(!isUgNumber(value) && !isEmptyString(value)) {
			return false; 
		}
		return true;        
	}, "<?php echo $this->translate("globale_phonenumber_format"); ?>");
		
	// basics custom failure and success url
	$("#profileform-store .savethenview").click(function() {
		$("#profileform-store .successurl").val('<?php echo encode($this->baseUrl('merchant/view/tab/store')); ?>');
		$("#profileform-store .failureurl").val('<?php echo encode($this->baseUrl('merchant/index/id/'.encode($merchant->getID()).'/tab/store')); ?>');
	});
	
	<?php if($merchant->isCompany()){ ?>
		// show the company only fields			
		disableContainerByClass("person");
		enableContainerByClass("company");
	<?php } ?>
	//trigger a click action on the selected radio button to enable and disable the approprate fields
	<?php if($merchant->isPerson()){ ?>
		// show the person only fields			
		disableContainerByClass("company");	
		enableContainerByClass("person");
	<?php } ?>
	
	var defaulturl = '<?php echo $merchant->getDefaultStore(); ?>';
	$('#url_pre').html(defaulturl);
	
	var def_username = 'username';
	<?php if(!isEmptyString($store->getUserName())){ ?>
		var def_username = '<?php echo $store->getUserName(); ?>';
	<?php } ?>
	$('#url_post').html(def_username);
	var saveurl = $('#url_pre').html()+$('#url_post').html();
	$('#url').val(saveurl);
	$('#username').keyup(function(){
		var current = $(this).val();
		$('#url_post').html(current);
		var saveurl = $('#url_pre').html()+$('#url_post').html();
		$('#url').val(saveurl);
	});
	
}); 
</script>
<style>

</style>
<?php if(!isSubscriber()){ ?>
<h1><?php echo $title; ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/merchant/leftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">   
        <div id="store">
            <form id="profileform-store" class="form-horizontal store" action="<?php echo $posturl; ?>" method="post">
            <?php if($request->tab == 'store'){ ?>
        	<div class="row makerelative" style="margin-left:0px;">
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <div id="store_actions" class="makeabsolute" style="top:-50px; right:10px;">
                    <table class="table border0 nohover margin0">                       
                       <tr>		                    
                            <td class="padding2"><button type="submit" class="btn btn-primary savethenview"><i class="icon-ok icon-white"></i> <?php echo $this->translate('global_button_save_changes'); ?></button>
                            </td>
                            <td class="padding2"><a href="<?php echo $this->baseUrl('merchant/view/id/'.encode($merchant->getID())); ?>" class="btn"><i class="icon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            </td>
                       </tr>
                    </table>
                </div>
                <span class="span6 marginleft0" style="width:98%;">
                    <div class="well lighter row marginleft0" style="padding-left:10px;">                        
                        <table class="table noborder profile">                       
							<tr>
                                <td style="width:45%;"><label class="control-label"><?php echo $this->translate("merchant_type_label"); ?>:</label><?php echo getMerchantType($merchant->getType()); ?></td>
                                <td>
                                    <label class="control-label"><?php echo $this->translate("merchant_category_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></label>
                                    <?php
                                        $allcats = getLevelOneCategories();
                                        $dropdown = new Zend_Form_Element_Select('categoryid',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allcats),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('span3')
                                                                
                                                            )
                                        );  
                                        $dropdown->setValue($merchant->getcategoryid()); 
                                        echo $dropdown->render();
                                    ?><div id="categoryid_error"></div>
                                </td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("merchant_storename_label"); ?>:<?php echo $this->translate("global_required_field_marker"); ?></label>
                                <input type="text" name="storename" id="storename" class="span3" value="<?php echo $store->getName(); ?>" /><div id="storename_error"></div></td>
                                <td><label class="control-label"><?php echo $this->translate("merchant_storeusername_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                	<input style="" maxlength="15" class="span2 strictalpha" name="username" id="username" type="text" value="<?php echo $store->getUserName(); ?>" />
                                	<label class='lineblocked'><a href="javascript: void(0);" class="btn btn-primary btn-mini" id='check_username_availability' title="Check Availability">Check</a></label>
                                <div id="username_error"></div><div id="username_availability_result" style="margin-top:5px;"></div></td>
                            </tr>
                            <tr>
                                <td colspan="2"><label class="control-label"><?php echo $this->translate("merchant_storeurl_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <input type="hidden" name="url" id="url" class="span3" value="" />
                                <span id="url_pre"></span><span id="url_post" class="bolded"></span>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="well lighter row marginleft0" style="padding-left:10px; margin-top:10px;">                        
                        <table class="table noborder profile">                       
                           <h3 class="well-legend margin0">Admin Contact</h3>
                           	<?php if($merchant->isCompany()){ ?>
                            <tbody class="company">
                                <tr>
                                	<td><label class="control-label"><?php echo $this->translate("merchant_company_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label><input type="text" name="orgname" id="orgname" class="span3" value="<?php echo $merchant->getorgname(); ?>" /><div id="orgname_error"></div></td>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_contact_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label><input type="text" name="contactperson" id="contactperson" class="span3" value="<?php echo $merchant->getcontactperson(); ?>" /><div id="contactperson_error"></div></td>
                                </tr>
                            </tbody>
                            <?php } ?> 
							<?php if($merchant->isPerson()){ ?>
                            <tbody class="person">
                                <tr>
                                    <td><label class="control-label" for="firstname"><?php echo $this->translate("merchant_firstname_label"); ?>:<?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <input type="text" name="firstname" id="firstname" class="span3" value="<?php echo $merchant->getFirstName(); ?>"  /><div id="firstname_error"></div></td>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_lastname_label"); ?>:<?php echo $this->translate("global_required_field_marker"); ?></label><input type="text" name="lastname" id="lastname" class="span3" value="<?php echo $merchant->getLastName(); ?>" /><div id="lastname_error"></div></td>
                                </tr>
                            </tbody>
                            <?php } ?> 
                            <tr>
                                <td style="width:45%;"><label class="control-label"><?php echo $this->translate("merchant_phone_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <div class="input-prepend">
                                        <span class="add-on"><?php echo '+'.COUNTRY_CODE_UG; ?></span><input name="phone" id="phone" type="text" maxlength="10" class="span2" style="width:110px; height:18px;" value="<?php echo getShortPhone($merchant->getPhone()); ?>" />
                                        
                                        <label class='lineblocked'><a href="javascript: void(0);" class="btn btn-primary btn-mini" id='check_phone_availability' title="Check Availability">Check</a></label><label class="pagedescription" style="font-size:10px;">e.g &nbsp; <span class="green">0772123456</span></label>
                                         <div id="phone_error"></div><div id="phone_availability_result" style="margin-top:5px;"></div>
                                    </div>
                                </td>
                                <td><label class="control-label" for="email"><?php echo $this->translate("merchant_email_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                    <input type="text" name="email" id="email" value="<?php echo $merchant->getEmail(); ?>" class="span3" style="" />
                                    <label class='lineblocked'><a href="javascript: void(0);" class="btn btn-primary btn-mini" id='check_user_availability' title="Check Availability">Check</a></label>
                                    <div id="email_error"></div><div id="email_availability_result" style="margin-top:5px;"></div>
                                    <input type="hidden" name="entityname" value="Merchant" />
                                    <input type="hidden" id="id" name="id" value="<?php echo encode($merchant->getID()); ?>" />
                                    <input type="hidden" id="thestoreid" name="thestoreid" value="<?php echo $store->getID(); ?>" />
                                    <input type="hidden" id="type" name="type" value="<?php echo $merchant->getType(); ?>" />                               
                                    <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" title="store" />
                                    <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" title="store" />
                                    <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="Profile updated successfully" />    
                                </td>
                            </tr>  
                        </table>
                    </div>
                    <div class="well lighter row marginleft0" style="padding-left:10px; margin-top:10px;">                        
                        <table class="table noborder profile">                       
                           <h3 class="well-legend margin0">Store Details</h3>
                            <tr>
                                <td><label class="control-label">Description<?php // echo $this->translate("merchant_store_description_label"); ?>:</label>	
								<textarea id="description" name="description" class="expanding xhtmleditor" style="width:95%;"><?php echo $store->getdescription(); ?></textarea><div id="description_error"></div></td>
                            </tr> 
                            <tr>
                                <td><label class="control-label">Tagline<?php // echo $this->translate("merchant_tagline_label"); ?>:</label>
                                <input type="text" name="tagline" id="tagline" class="span3" value="<?php echo $store->getTagline(); ?>"  /><div id="tagline_error"></div></td>
                            </tr> 
                        </table>
                    </div>
                </span> 
                
        	</div>
            <?php } ?>
        	</form> 
        </div>
        <div id="products">
            <h2>Products</h2>
            <form id="profileform-products" class="form-horizontal products">
                <?php if($request->tab == 'products'){ ?>
                <div class="row" style="margin-left:0px;">
                	<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                    
                </div>
                <?php } ?>
            </form>
        </div>
        <div id="image">
            <h2>Images</h2>
            <form id="profileform-image" class="form-horizontal image">
                <?php if($request->tab == 'image'){ ?>
                <div class="row" style="margin-left:0px;">
                	<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                    
                </div>
                <?php } ?>
            </form>
        </div>
        <div id="account">
        	<h2>Settings</h2>
            <form id="profileform-farm" class="form-horizontal account">
                <?php if($request->tab == 'account'){ ?>
            		
            	<?php } ?>
            </form>
        </div>
    </div> 
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
