<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$controller = $request->getControllerName();
	$action = $request->getActionName();
	if($controller == 'profile' && isEmptyString($request->tab)){
		$request->setParam('tab', 'basics'); 
	}
	// debugMessage($user->toArray());
?>
<script>
$(document).ready(function() {
	// override default tab
	<?php if(!isEmptyString($request->tab)){ ?>
		$("#tabs").tabs({ selected:'<?php echo $request->tab; ?>', fx: {opacity: 'toggle'} });	   
	<?php } ?>
	$('#tabs').tabs({
		// the selected tab
		selected: '<?php echo $request->tab; ?>'
	});
	
	$("#tabs ul#leftnav li a").click(function(e){
		var currentclass = $(this).attr('class');
		var oldclass = '<?php echo $request->tab; ?>';
		if(currentclass != oldclass || currentclass == 'subscription'){
			$(".form-horizontal."+currentclass).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block'});
			var url = '';
			var controller = '<?php echo $controller; ?>';
			var action = '<?php echo $action; ?>';
			var ismerchant = '<?php echo isMerchant() ? 1 : 0; ?>';
			if(controller == 'merchant' && action == 'index'){
				var url = "<?php echo $this->baseUrl("merchant/index/id/".encode($merchant->getID())."/tab/"); ?>"+currentclass;
			}
			if((controller == 'merchant' && action == 'view') || currentclass == 'account'){
				var url = "<?php echo $this->baseUrl("merchant/view/id/".encode($merchant->getID())."/tab/"); ?>"+currentclass;
			}
			if((currentclass == 'products')){
				var url = "<?php echo $this->baseUrl("product/list"); ?>";
			}
			if(!isEmptyString(url)){
				location.href = url;  
			}
		}
	});
	
	$("#tabs").tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
	$("#tabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	
}); 
</script>
<div class="span3 marginleft0" id="left">    
    <ul id="leftnav" style="width:97%;">
        <li id="tab_store"><a href="#store" class="store">Store</a></li>
        <li id="tab_account"><a href="#products" class="products">Products</a></li> 
        <li id="tab_account"><a href="#account" class="account">Account Settings</a></li>   
    </ul>
</div>
