<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$merchant = new Merchant();
	
	$id = decode($request->id);
	$merchant->populate($id);
	$store = $merchant->getStore();
	
	if(isEmptyString($request->tab)) {
		$request->setParam('tab', 'store');
	}
	
	$title = 'My Store';
	if(!isMerchant()){
		$title = "Merchant: ".$merchant->getName();
	}
	$this->headTitle($title);
	
?>

<script>
$(document).ready(function() {
	
	
}); 
</script>
<style>

</style>
<?php if(!isSubscriber()){ ?>
<h1><?php echo $title; ?></h1>
<?php } ?>
<div id="tabs">
    <?php require APPLICATION_PATH."/views/scripts/merchant/profileleftcolumn.phtml"; ?>
    <div class="span9 tab-content" id="center">   
        <div id="store">
            <form id="profileform-store" class="form-horizontal store">
            <?php if($request->tab == 'store'){ ?>
        	<div class="row makerelative" style="margin-left:0px;">
                <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                    <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                <?php } ?>
                <div id="store_actions" class="makeabsolute" style="top:-40px; right:0;">
                    <table class="table border0 nohover margin0">                       
                       <tr>		                    
                            <td class="padding2"><a class="btn btn-primary" href="<?php echo $this->baseUrl('merchant/index/id/'.encode($id)); ?>" id="update"><i class="icon-pencil icon-white"></i> Update</a> &nbsp;
                            </td>
                            <?php if(!$merchant->isApproved()){ ?>
                            <td class="padding2"><a class="btn btn-primary approve" style="width:65px;" theid="<?php echo $id; ?>" action="<?php echo $this->baseUrl('merchant/approve/id/'.encode($id).'/status/1/successurl/'.encode($this->baseUrl('merchant/view/id/'.encode($id)))); ?>" href="javascript:doNothing();" title="Approve" merchant="<?php echo $merchant->getName(); ?>"><i class="icon-ok icon-white"></i> Approve</a> &nbsp;
                            </td>
                            <?php } ?>
                            <?php if(isAdmin()){ ?>
                            <td class="padding2"><a class="btn" href="<?php echo $this->baseUrl('merchant/list'); ?>" title="List Merchants"><i class="icon-list"></i> List</a> &nbsp;
                            </td>
                            <?php } ?>
                       </tr>
                    </table>
                </div>
                <span class="span6 marginleft0" style="width:98%;">
                    <div class="well lighter row marginleft0" style="padding-left:10px;">                        
                        <table class="table noborder profile">                       
							<tr>
                                <td style="width:45%;"><label class="control-label"><?php echo $this->translate("merchant_type_label"); ?>:</label><?php echo getMerchantType($merchant->getType()); ?></td>
                                <td><label class="control-label"><?php echo $this->translate("merchant_category_label"); ?>:</label><?php echo getLevelOneCategories($merchant->getcategory()); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("merchant_storename_label"); ?>:</label><?php echo $store->getName(); ?></td>
                                <td><label class="control-label"><?php echo $this->translate("merchant_storeusername_label"); ?>:</label><?php echo $store->getUserName(); ?></td>
                            </tr>
                            <tr>
                                <td><label class="control-label"><?php echo $this->translate("merchant_storeurl_label"); ?>:</label><?php echo $store->getUrl(); ?></td>
                                <td></td>
                            </tr>
                        </table>
                    </div>
                    <div class="well lighter row marginleft0" style="padding-left:10px; margin-top:10px;">                        
                        <table class="table noborder profile">                       
                           <h3 class="well-legend margin0">Admin Contact</h3>
                           	<?php if($merchant->isCompany()){ ?>
                            <tbody class="person">
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_company_label"); ?>:</label>
                                    <?php echo $merchant->getorgname(); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_contact_label"); ?>:</label>
                                    <?php echo $merchant->getcontactperson(); ?></td>
                                </tr>
                            </tbody>
                            <?php } ?> 
							<?php if($merchant->isPerson()){ ?>
                            <tbody class="person">
                                <tr>
                                    <td><label class="control-label" for="firstname"><?php echo $this->translate("merchant_firstname_label"); ?>:</label>
                                    <?php echo $merchant->getFirstName(); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_lastname_label"); ?>:</label>
									<?php echo $merchant->getLastName(); ?></td>
                                </tr>
                            </tbody>
                            <?php } ?> 
                            <tr>
                                <td style="width:45%;"><label class="control-label"><?php echo $this->translate("merchant_phone_label"); ?>:</label>
                                    <?php echo isEmptyString($merchant->getPhone()) ? '--' : getShortPhone($merchant->getPhone()); ?>
                                </td>
                                <td><label class="control-label" for="email"><?php echo $this->translate("merchant_email_label"); ?>:</label>
                                    <?php echo isEmptyString($merchant->getEmail()) ? '--' : $merchant->getEmail(); ?>
                                </td>
                            </tr> 
                        </table>
                    </div>
                </span> 
        	</div>
            <?php } ?>
        	</form> 
        </div>
        <div id="products">
            <h2>Products</h2>
            <form id="profileform-products" class="form-horizontal products">
                <?php if($request->tab == 'products'){ ?>
                <div class="row" style="margin-left:0px;">
                	<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                        <div class="alert alert-success"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                    
                </div>
                <?php } ?>
            </form>
        </div>
        <div id="account">
        	<h2>Settings</h2>
            <form id="profileform-farm" class="form-horizontal account">
                <?php if($request->tab == 'account'){ ?>
            		<span class="span6 marginleft0" style="width:98%;">
                        <div class="well lighter row marginleft0" style="padding-left:10px; margin-top:10px;">                        
                            <table class="table noborder profile">                       
                               <h3 class="well-legend margin0">Store Status</h3>
                                <tr>
                                    <td style="width:45%;"><label class="control-label"><?php echo $this->translate("merchant_status_label"); ?>:</label>
                                        <?php echo isEmptyString($merchant->getStatus()) ? '--' : getMerchantApprovalStatus($merchant->getStatus()); ?>
                                    </td>
                                    <td>
                                    
                                    </td>
                                </tr> 
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_dateapproved_label"); ?>:</label>
                                        <?php echo isEmptyString($merchant->getDateApproved()) ? '--' : $merchant->getDateApproved(); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_approvedby_label"); ?>:</label>
                                        <?php echo isEmptyString($merchant->getApprovedByID()) ? '--' : $merchant->getApprover()->getName(); ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_dateadded_label"); ?>:</label>
                                        <?php echo isEmptyString($merchant->getDateCreated()) ? '--' : date('d/m/Y H:i', strtotime($merchant->getDateCreated())); ?></td>
                                    <td><label class="control-label"><?php echo $this->translate("merchant_addedby_label"); ?>:</label>
                                        <?php echo $merchant->getCreator()->getName(); ?>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div class="well lighter row marginleft0" style="padding-left:10px; margin-top:10px;">                        
                            <table class="table noborder profile">                       
                               <h3 class="well-legend margin0">Store Users</h3>
                               
                            </table>
                        </div>
                     </span>
            	<?php } ?>
            </form>
        </div>
    </div> 
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
