<?php
	require_once APPLICATION_PATH.'/includes/header.php';
?>
<table class="noborder margin0" id="footertable">
    <tr>
    	<td colspan="3" style="padding-top:15px; padding-left:75px; width:50%;">
        	<p style="text-align:left;"><?php echo sprintf($this->translate("copyright"), date("Y"), $this->translate("companyname")); ?>.</p>
        </td>
        <td style="padding:25px 0;">
        	<div style="position:relative; padding-right:50px; display:block;">
            	<ul id="bottomrightlinks">
                    <li><a href="<?php echo $this->baseUrl('aboutus/termsofservice'); ?>"><span>Terms of Use</span></a></li>
                    <li><a href="<?php echo $this->baseUrl('aboutus/privacypolicy'); ?>"><span>Privacy Policy</span></a></li>
                    <li><a href="<?php echo $this->baseUrl('faqs'); ?>" title="Frequently Asked Questions"><span>FAQs</span></a></li>
                </ul>
            </div>
        </td>
    </tr>
</table>
<script>
//Use window.load and not document.ready for effective equal heights
$(window).load(function() {
	<?php if($showloading){ ?>
		$('#dvLoading').fadeOut(500);
	<?php } ?>
}); 
</script>
<?php
	$session->setVar('newsletter_success', '');
	$session->setVar('newsletter_error', '');
	require_once APPLICATION_PATH.'/includes/footer.php';
?>