<?php
	require_once APPLICATION_PATH.'/includes/header.php';
?>
<style>
#footertable td.section {
	width:24%;
	vertical-align:top;
	padding:8px;
}
h2.footerheading {
	color:#fff;
	font-size:17px;
	font-weight:bold;
	border-bottom:1px solid #c8c8c5;
	padding-bottom:5px;
	margin-bottom:10px;
	width:80%;
	line-height:24px;
}
#newletterbg {
	width:100%; 
	background-color:#f1f1f1; 
	min-height:50px; 
	padding:10px 0 0 5px; 
	khtml-border-radius: 3px; 
	-moz-border-radius: 3px; 
	-opera-border-radius: 3px; 
	-webkit-border-radius: 3px; 
	border-radius: 3px;
}
#receivemail {
	display:inline-block; 
	font-size:16px; 
	line-height:24px; 
	color:#e4eae4; 
	padding:15px 0 10px 0; 
	width:100%;
}
ul.footerlinks {
	list-style:none;
	margin:10px 0 0 5px;;
	padding:0;
}
ul.footerlinks li {
	display:block;
	padding:0;
	margin:0;
	height:auto;
	position:relative;
}
ul.footerlinks li > a {
	font-size:16px;
	padding:8px 0;
	display:block;
	width:95%;
	font-family:'calibri','Telex',sans-serif;
}
ul.footerlinks.connect li {
	padding-left:10px;	
}
ul.footerlinks.connect li img {
	position:absolute; 
	left:0; top:10px;
}
ul.footerlinks.connect li span {
	padding-left:20px;
}
#bottomrightlinks {
	list-style:none; 
	margin:0; 
	padding:0; 
	position:absolute; 
	bottom:5px;
	left:5px;
}
#bottomrightlinks li {
	float:left;
	border-right:1px solid #908e8e;
}
#bottomrightlinks li:last-child {
	border-right:none;	
}
#bottomrightlinks li a {
	padding:5px 10px;
}
</style>
<table class="noborder margin0" id="footertable">
	<tr>
    	<td class="section">
        	<h2 class="footerheading calfont">Quick Links</h2>
            <ul class="footerlinks">
            	<li><a href="#"><span>Link 1</span></a></li>
                <li><a href="#"><span>Link 2</span></a></li>
                <li><a href="#"><span>Link 3</span></a></li>
                <li><a href="#"><span>Link 4</span></a></li>
            </ul>
        </td>
        <td class="section">
        	<h2 class="footerheading calfont">Partners</h2>
            <ul class="footerlinks">
            	<li><a href="#" target="_blank"><span>Link 1</span></a></li>
                <li><a href="#" target="_blank"><span>Link 2</span></a></li>
                <li><a href="#" target="_blank"><span>Link 3</span></a></li>
                <li><a href="#" target="_blank"><span>Link 4</span></a></li>
            </ul>
        </td>
        <td class="section" style="width:23%;">
        	<h2 class="footerheading calfont">TBD</h2>
            <ul class="footerlinks connect">
            	<li><a href="#" target="_blank"><span>Link 1</span></a></li>
                <li><a href="#" target="_blank"><span>Link 2</span></a></li>
                <li><a href="#" target="_blank"><span>Link 3</span></a></li>
                <li><a href="#" target="_blank"><span>Link 4</span></a></li>
            </ul>
        </td>
        <td class="section" style="border-left:2px solid #838181; padding-left:20px; width:auto;">
        	
        </td>
    </tr>
    <tr>
    	<td colspan="3" style="padding:0; height:30px; padding-right:40px;">
        	<p style="color:#8ca77f; text-align:center; "><?php echo sprintf($this->translate("copyright"), date("Y"), 'Company Name'); ?>.</p>
        </td>
        <td style="padding:15px 0 0 15px;">
        	<div style="position:relative; display:block;">
            	<ul id="bottomrightlinks">
                    <li><a href="<?php echo $this->baseUrl('aboutus/termsofservice'); ?>"><span>Terms of Use</span></a></li>
                    <li><a href="<?php echo $this->baseUrl('aboutus/privacypolicy'); ?>"><span>Privacy Policy</span></a></li>
                    <li><a href="<?php echo $this->baseUrl('faqs'); ?>" title="Frequently Asked Questions"><span>FAQs</span></a></li>
                </ul>
            </div>
        </td>
    </tr>
</table>
<script>
//Use window.load and not document.ready for effective equal heights
$(window).load(function() {
	<?php if($showloading){ ?>
		$('#dvLoading').fadeOut(500);
	<?php } ?>
}); 
</script>
<?php
	$session->setVar('newsletter_success', '');
	$session->setVar('newsletter_error', '');
	require_once APPLICATION_PATH.'/includes/footer.php';
?>