<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	$user->populate($session->getVar('userid'));
	
	$thecontroller = $request->getControllerName();
	$theaction = $request->getActionName();
	$publiccontrollers = array("index", "signup","aboutus","howitworks","benefits","news","help","user","tour","forum","faqs","testimonials","billing"); 
	if(isEmptyString($userid)){
		$publiccontrollers[] = 'contactus';
	}
	
	$logopath = $this->baseUrl('images/logo.png');
	$logostyle = ' style="width:auto; margin-top:25px;"';
	if (in_array($thecontroller, $publiccontrollers)){
		$logopath = $this->baseUrl('images/logo.png');
		$logostyle = ' style="width:auto; margin-top:25px;"';
	}
	
?>

<div class="container makerelative">
  <ul id="headerwrapper">
  	<li style="width:22%; float:left;">
    	<a class="brand" id="thelogo" href="<?php echo $this->baseUrl('index'); ?>"><img <?php echo $logostyle; ?> src="<?php echo $logopath; ?>" /></a>
    </li>
    <li style="width:77%; float:right; padding-top:2px;">
    	<div class="maxwidth" style="height:40px; margin-bottom:5px;">
            	<ul class="nav maxwidth" id="headeractions">
                	<li style="width:70%; float:left;" class="maxheight">
                    	<?php if(!isEmptyString($userid)){ ?>
                        <div class="contentArea">
                            <input type="text" class="search" id="inputSearch" placeholder="Search...<?php // echo $searchplaceholder; ?>" />
                            <ul id="divResult" style="list-style:none; margin-left:0; margin-top:-10px;"></ul>
                        </div>
                        <?php } ?>
                    </li>
                    <li style="width:28%; float:right;" class="dropdown maxheight">
						<?php if(!isEmptyString($userid)){ ?>
                            <a style="text-align:center;" data-toggle="dropdown" id="accountdrop" class="dropdown-toggle <?php echo !in_array($thecontroller, $publiccontrollers) ? 'loggedin' : ''; ?>" href="#"><?php echo $user->getName(); ?> <b class="caret"></b></a>
                            <ul class="dropdown-menu span3">
                                <li>
                                <li><a href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())); ?>" title="My Profile">My Profile</a></li>                                <li><a href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())."/tab/account"); ?>" title="Account Settings">Account Settings</a></li>
                                <li><a href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())."/tab/account"); ?>" title="Change Password">Change Password</a></li>    
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->baseUrl("faqs"); ?>" title="Get Help">Get Help</a></li>
                                <li><a href="<?php echo $this->baseUrl("contactus"); ?>" title="Contact Us">Contact Us</a></li>
                                <li class="divider"></li>
                                <li><a href="<?php echo $this->baseUrl("user/logout"); ?>" title="Logout">Logout</a></li>
                            </ul>
                         <?php } else { ?>
                         	<ul class="nav pull-right" id="headeractions">
                                <li id="loginheader" style="float:right;">
                                    <a class="btn" style="display:inline-block; font-weight:normal; color:#000; padding:6px 10px;" id="headersignup" type="submit" href="<?php echo $this->baseUrl('signup'); ?>"><i class="icon-user"></i> Signup</a>&nbsp;
                                    <a class="btn btn-primary" style="display:inline-block; font-weight:normal; padding:6px 10px;" id="headersignin" type="submit" href="<?php echo $this->baseUrl('user/login'); ?>"><i class="icon-lock icon-white"></i> Signin</a>
                                </li>
                            </ul>    
						 <?php ?>
                    </li>
                </ul>
            <?php } ?>
        </div>
        <div class="maxwidth" style="height:60px;" >
        	<?php if (in_array($thecontroller, $publiccontrollers)){ ?>
                <div class="subnavbar pull-left <?php echo !in_array($thecontroller, $publiccontrollers) ? 'loggedin' : ''; ?>" id="thenav">
                    <?php require_once APPLICATION_PATH.'/views/scripts/index/headermenu.phtml'; ?>
                </div>
            <?php } else { ?>
                <div class="subnavbar pull-left <?php echo !in_array($thecontroller, $publiccontrollers) ? 'loggedin' : ''; ?>" id="thenav">
                    <?php require_once APPLICATION_PATH.'/views/scripts/index/headermenu.phtml'; ?>
                </div>
            <?php } ?>
        </div>
    </li>
  </ul>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
