<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$thecontroller = $request->getControllerName();
	$theaction = $request->getActionName();

	$publiccontrollers = array("index", "signup","aboutus","howitworks","benefits","news","help","user","tour","forum","faqs","testimonials","billing"); 
	if(isEmptyString($userid)){
		$publiccontrollers[] = 'contactus';
	}
	
	$isstore = false;
	$isstorecontroller = false;
	if(in_array($request->getControllerName(), $storecontrollers)){ 
		$isstorecontroller = true;
		$store = new Store();
		$store->findByUsername($this->store);
		$storeurl = $store->getMerchant()->getDefaultStore();
		if(!isEmptyString($store->getID())){ 
			// debugMessage($store->toArray());
			$isstore = true;
			$storeurl = $this->baseUrl('store/'.$store->getUserName());
			$categories = getLevelTwoCategoriesForStore($store->getID());
		}
	}
?>
<ul class="mainnav" id="middlebar">
<?php if(isEmptyString($session->getVar('userid')) && !$isstore){ ?>
	<li class="<?php echo ($request->getControllerName() == 'index') ? 'active' : ''; ?>">
		<a href="<?php echo $this->baseUrl('index'); ?>"><span>Home</span></a>	
	</li>
    <li class=""><a><span>All Products</span></a></li>	
    <li class=""><a><span>Categories</span></a></li>	
<?php } ?>
<?php if(!isEmptyString($session->getVar('userid')) && !$isstore){ ?>
	<li class="<?php echo ($request->getControllerName() == 'dashboard') ? 'active' : ''; ?>">
		<a href="<?php echo $this->baseUrl('dashboard'); ?>"><span>Dashboard</span></a>	
	</li>
<?php } ?>

<?php if(!isEmptyString($session->getVar('userid')) && !$isstore){ ?>
	<?php if(isMerchant()){ 
		$store = $user->getMerchant()->getStore();
	?>
		<li class="<?php echo (($request->getControllerName() == 'product')) ? 'active' : ''; ?>">
			<a href="<?php echo $this->baseUrl('product/list'); ?>"><span>Products</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'order')) ? 'active' : ''; ?>">
			<a><span>Customer Orders</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'payment')) ? 'active' : ''; ?>">
			<a><span>Payments</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'store')) ? 'active' : ''; ?>">
			<a href="<?php echo $this->baseUrl('merchant/view/id/'.encode($user->getMerchantID())); ?>"><span>Store Profile</span></a>	
		</li>
		<li class="">
			<a href="<?php echo $store->getProfilePath(); ?>" target="_blank" title="Go to Shopping Front" ><span>Store Front</span></a>	
		</li>
	<?php } ?>
	<?php if(isSubscriber()){ ?>
		<li class="<?php echo (($request->getControllerName() == 'profile'  && $request->getActionName() != 'list') || $request->getControllerName() == 'profile') ? 'active' : ''; ?>">
			<a href="<?php echo $this->baseUrl('profile/view/id/'.encode($session->getVar('userid'))); ?>"><span>My Profile</span></a>	
		</li>
	<?php } ?>
	<?php if(isAdmin()){ ?>
		<li class="<?php echo (($request->getControllerName() == 'merchant')) ? 'active' : ''; ?>">
			<a href="<?php echo $this->baseUrl('merchant/list'); ?>"><span>Merchants</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'profile')) ? 'active' : ''; ?>">
			<a href="<?php echo $this->baseUrl('profile/list'); ?>"><span>Users</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'product')) ? 'active' : ''; ?>">
			<a href="<?php echo $this->baseUrl('product/list'); ?>"><span>Products</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'payment')) ? 'active' : ''; ?>">
			<a><span>Payments</span></a>	
		</li>
		<li class="<?php echo (($request->getControllerName() == 'appconfig')) ? 'active' : ''; ?>">
			<a><span>System Config</span></a>	
		</li>
	<?php } ?>
<?php } ?>
<?php if($isstorecontroller && $isstore){ ?>    
    <li class=""><a href="<?php echo $storeurl; ?>"><span><?php echo $store->isTextLogo() ? 'Home' : $store->getName(); ?></span></a></li>
    <?php if($isstore){ ?>
         <?php if($store->isProdductMenu()){ 
                $products = $store->getProducts();
            ?>
            <li class=""><a href="<?php echo $this->baseUrl('store/products/id/'.encode($store->getID())); ?>"><span>All Products</span></a></li>	    	
            <?php if($products->count() > 0){ ?>
                <?php foreach($products as $product){ ?>
                    <li id="prod_<?php echo $product->getID(); ?>" class=""><a href="<?php echo $this->baseUrl('store/product/id/'.encode($product->getID())); ?>"><span><?php echo $product->getName(); ?></span></a></li>	
                <?php } ?>
            <?php } ?>
        <?php } else { ?>  
            <?php    
                $categories = getLevelTwoCategoriesForStore($store->getID());
             ?>
             <li class=""><a href="<?php echo $this->baseUrl('store/products/id/'.encode($store->getID())); ?>"><span>All Products</span></a></li>	    	
             <?php if(count($categories) > 0){ ?>
                <?php foreach($categories as $key => $value){ 
                        $category = new Category();
                        $category->populate($key);
                        $alias = $category->getAlias();
                        if(isEmptyString($alias)){ 
                            $alias = strtolower($value);
                        }
                ?>
                    <li id="cat_<?php echo $key; ?>" class=""><a href="<?php echo $this->baseUrl('storecategory/view/cat/'.$alias.'/id/'.encode($key)); ?>"><span><?php echo $value; ?></span></a></li>	
                <?php } ?>
             <?php } ?>
        <?php } ?>    
    <?php } ?>
<?php } ?>    
</ul>