<?php
	require_once APPLICATION_PATH.'/includes/header.php';
		
	$title = $this->translate("dashboard_pagetitle");
	// meta data
	$this->headTitle($title); 
	
	$user = new UserAccount();
	$user->populate($userid);
?>
<script>
$(document).ready(function(){
	
});
</script>
<style>
#contentcolumn {
	padding:10px;
	width:auto;
}
#dashleft {
	margin:0 5px 0 0;
	width:98%;
	float:left;
}
#dashleft .widgetsection {
	width:100%;
}
#dashright {
	width:29%;
	margin:0;
	padding:0;
}
.widgetsection {
	margin-bottom:10px;
}
.widgetsection h3 {
	font-size:15px;
}

</style>	
<div class="blocked clear maxwidth">
    <div id="centercolumn" style="width:100%;">
        <div class="blocked maxwidth">
            <div class="pull-left" id="dashleft">
                <div class="widgetsection makerelative" style="min-height:130px;">
                    <h3 style="color:#00436D;"><?php echo isAdmin() ? 'Admin Dashboard' : 'Welcome '.$user->getFirstName(); ?></h3>
                    <div>
                    
                    </div>
                </div>
                <div class="widgetsection height300">
                    <h3 style="color:#00436D;">At a Glance</h3>
                    <div>
                    
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
