<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$store = new Store();
	$id = decode($request->getParam('id'));
	if(!isEmptyString($id)){
		$store->populate($id);
		// debugMessage($product->toArray());
	}
	
	$cart = $this->cart;
	// debugMessage($cart);
	
	$title = 'Pay Now';
	$pagetitle = $title.' | '.$store->getName();
	$this->headTitle($pagetitle);
	
?>
<script>
$(document).ready(function(){	
	// add item to cart
	
});
</script>
<style>
#contentcolumn {
	padding:15px 10px 15px 10px;
	width:auto;
}
</style>
<div class="row margin0">
    <div style="width:75%; float:left;">
        <ul class="default widget">
            <li style="width:100%; min-height:200px;">
                <h2><?php echo $title; ?></h2>
                
                <div class="row margin0">
                    <label class="bordered blocked" style="margin:10px 10px; padding:10px 0; height:30px; width:auto;">
                    	<a href="<?php echo $this->baseUrl('store/cart/id/'.encode($store->getID())); ?>" class="btn pull-left" style="margin-left:15px;"><i class="icon-arrow-left"></i> Return to Cart</a>
                        <a href="<?php echo $store->getProfilePath(); ?>" class="btn btn-primary pull-right" style="margin-right:15px;"><i class="icon-ok icon-white"></i> Pay</a>
                    </label>
                </div>
            </li>
        </ul>
    </div>
    <div style="width:23%; float:right;">
    
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
