<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Category";
	$category = new Category();
	$store = new Store();
	
	$id = decode($request->getParam('id'));
	if(!isEmptyString($id)){
		$category->populate($id);
		// debugMessage($category->toArray());
		$store = $category->getStore();
	}
	$merchant = $store->getMerchant();
	
	$isstore = false;
	if(!isEmptyString($category->getID())){
		$isstore = true;
		$categoryname = $category->getName();
		// '<a href="'.$merchant->getProfilePath().'">'.$store->getName().'</a> > ';
		$title = $category->getName();
		if($category->isLevel2()){
			$title = 'Categories > '.$category->getName();
		}
		if($category->isLevel3()){
			$title = 'Categories > <a href="'.$this->baseUrl('storecategory/view/cat/'.$category->getParent()->getName().'/id/'.encode($category->getParentID())).'">'.$category->getParent()->getName().'</a> > '.$category->getName();
		}
		
		$pagetitle = $category->getName()." | ".$store->getName();
		// debugMessage($store->getMerchant()->toArray());
	} else {
		$category = $title = $pagetitle = $request->getParam('cat');
	}
	
	$level1_categories = getLevelThreeCategories($store->getID(), $category->getID());
	// debugMessage($level1_categories);
	
	$this->headTitle($pagetitle);
	
?>

<style>
#contentcolumn {
	padding:15px 10px 15px 10px;
	width:auto;
}
</style>
<div>
    <?php if(!$isstore){ ?>
    	<h1><?php echo $title; ?></h1>
    	<div style="padding:20px 5px;" class="alert alert-info clear margin0 centeralign">The store <b><?php echo $category; ?></b> does not exist</div>
    <?php } else { ?>
    	<div style="width:75%; float:left;">
            <ul class="default widget">
                <li style="width:100%; min-height:200px;">
                    <h2><?php echo $title; ?></h2>
                   
					<?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
                        <div class="alert alert-success" style="margin:5px;"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
                    <?php } ?>
                    <table class="table nohover margin0 border0" style="margin:0 20px 0 15px; width:95%;">
                    	<tr>
                        	<td>
                            	<?php if($category->isLevel2()){ ?>
                                    <ul class="default" style="margin-top:5px; margin-bottom:10px; margin-left:10px;">
                                        <?php 
                                            foreach($level1_categories as $key => $value){
                                                $cat = new Category();
                                                $cat->populate($key);
                                                $viewurl = $this->baseUrl('storecategory/view/cat/'.$cat->getName().'/id/'.encode($cat->getID()));
                                        ?>
                                        <li class="imagecontainer nobg" style="width:160px; height:150px; margin-right:15px; padding:10px; border-color:#E1E0E0;">
                                            <label class="blocked maxwidth bolded centeralign" style="font-size:12px;"><a href="<?php echo $viewurl; ?>" title="Details"><?php echo $cat->getName(); ?></a></label>
                                            <a href="<?php echo $viewurl; ?>" title="Details" class="blocked">
                                                <div class="thumbinfo" style="background-color:#fff; border-color:#dddddd; height:80px; width:95px;"> 
                                                    <img class="profileimage" src="<?php // echo $product->getThumbnailPicturePath(); ?>" />
                                                </div>
                                            </a>
                                            <table class="table margin0 padding2 nohover nobg border0" style="margin-left:25px; width:auto; margin-top:10px;">
                                                <tr>
                                                    <td class="centeralign"><a href="<?php echo $viewurl; ?>" title="View Products" class="btn btn-primary btn-mini"><i class="icon-white icon-plus"></i> View Products</a></td>
                                                </tr>
                                            </table>
                                        </li>
                                        <?php } ?>
                                    </ul>
                                 <?php } ?>
                                 <?php if($category->isLevel3()){ ?>
                                 	<?php 
										$products = $category->getStoreProducts($store->getID());
									?>
                                 	<?php if($products->count() == 0){ ?>
                                    	<div style="padding:10px 5px;" class="alert alert-info clear margin0 centeralign">There are no items to list under <b><?php echo $category->getName(); ?></b></div>
                                    <?php } else { ?>
                                        <ul class="default" style="margin-top:5px; margin-bottom:10px; margin-left:10px;">
                                            <?php 
                                                foreach($products as $product){
                                                    // $product = $productline->getProduct();
                                                    $viewurl = $this->baseUrl('store/product/id/'.encode($product->getID()));
                                            ?>
                                                <li class="imagecontainer nobg" style="width:160px; height:180px; margin-right:15px; padding:10px; border-color:#E1E0E0;">
                                                    <label class="blocked maxwidth bolded centeralign" style="font-size:12px;"><a href="<?php echo $viewurl; ?>" title="Details"><?php echo $product->getName(); ?></a></label>
                                                    <div class="thumbinfo" style="background-color:#fff; border-color:#dddddd; margin-left:45px;"> 
                                                        <a href="<?php echo $viewurl; ?>" title="Details" class="blocked"><img class="profileimage" src="<?php echo $product->getThumbnailPicturePath(); ?>" /></a>
                                                    </div>
                                                    <table class="table margin0 padding2 nohover nobg" style="margin-left:30px; width:auto;">
                                                        <tr>
                                                            <td class="centeralign"><span class="blocked bolded"><?php echo formatNumber($product->getCost()); ?> shs</span></td>
                                                        </tr>
                                                        <tr>
                                                            <td class="centeralign"><a href="<?php echo $this->baseUrl('store/cart/id/'.encode($store->getID()).'/pid/'.encode($product->getID())); ?>" title="Add to Cart" class="btn btn-primary btn-mini"><i class="icon-white icon-plus"></i> Add to Cart</a></td>
                                                        </tr>
                                                        <tr>
                                                            <td class="centeralign"><a href="<?php echo $this->baseUrl('store/watchlist/id/'.encode($store->getID()).'/pid/'.encode($product->getID())); ?>" title="Add to Watch List" class="centeralign">Add to Watch List</a></td>
                                                        </tr>
                                                    </table>
                                                </li>
                                            <?php } ?>
                                        </ul>
                                    	<?php } ?>
                           		<?php } ?>    
                            </td>
                        </tr>
                    </table>
               	</li>
            </ul>
       	</div>
    <?php } ?>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
