<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$product = new Product();
	$storeid = decode($request->storeid);
	if(!isEmptyString($storeid)){
		$product->setStoreID($storeid);
	}
	$product->setType(1);
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$product->processPost($session->getVar(FORM_VALUES));	
	}
	$store = $product->getStore();
	
?>
<script>
	$(document).ready(function() {
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				name: "required",
				refno: "required",
				cost: "required",
				categoryid: "required",
				type: "required",
				storeid: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				name: "<?php echo $this->translate("product_name_error"); ?>",
				refno: "<?php echo $this->translate("product_refno_error"); ?>",
				cost: "<?php echo $this->translate("product_cost_error"); ?>",
				categoryid: "<?php echo $this->translate("product_category_error"); ?>",
				type: "<?php echo $this->translate("product_type_error"); ?>",
				storeid: "<?php echo $this->translate("product_storeid_error"); ?>"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						error.appendTo("#"+element.attr("name")+"_error")
						break;
				}			
			}
		});
		
		$('#cost').keyup(function(){
			var cost = $(this).val();
			var rate = $('#trxrate').val();
			var computedtrxfee = IsValidAmount(cost) ? (rate/100)*cost : 0;
			var computedtrxfee_round = Math.round(computedtrxfee)
			var netprice = cost - computedtrxfee_round;
			// alert(computedrate);
			$("#trxfee_display").html(addCommas(computedtrxfee_round));
			$("#trxfee").val(computedtrxfee_round);
			$("#netprice_display").html(addCommas(netprice));
			$("#netprice").val(netprice);
		});
		$('#cost').trigger('keyup');
		
	}); 
</script>
<style>
body {
	overflow:hidden;
}
</style>
<div class="popupdiv">
<form class="form-horizontal well span6" id="indexform" action="<?php echo $this->baseUrl("merchant/create"); ?>" method="post">
	<input type="hidden" name="entityname" value="Product" />
    <input type="hidden" id="id" name="id" value="<?php echo encode($product->getID()); ?>" />
    <input type="hidden" name="<?php echo SUCCESS_MESSAGE; ?>" value="global_save_success" />
    <input type="hidden" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('index/addsuccess')); ?>" />
    <input type="hidden" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($this->baseUrl('index/adderror')); ?>" />
    <input type="hidden" name="popupadd" value="1" />
    <table class="table">
		<?php if($sessionhaserror) { ?>
	        <tr>
	        	<td colspan="2"><div class="alert alert-error"><?php echo $session->getVar(ERROR_MESSAGE); ?></div></td>
	        </tr>
        <?php } ?>
        <tr>
            <td style="width:20%;"><label class="control-label"><?php echo $this->translate("product_type_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td>
            	<?php
                    $values = getProductTypes();
                    $dropdown = new Zend_Form_Element_Select('type',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $values),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('width200')
											
                                        )
                    );  
                    $dropdown->setValue($product->getType()); 
                    echo $dropdown->render();
                ?><div id="type_error"></div>
            </td>
        </tr>
        <tr>
            <td><label class="control-label"><?php echo $this->translate("product_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
        	<td><input type="text" name="name" id="name" class="span3" value="" /><div id="name_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label"><?php echo $this->translate("product_refno_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
        	<td><input type="text" name="refno" id="refno" class="span3" value="" /><div id="refno_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label">Cost (Ugx): <?php echo $this->translate("global_required_field_marker"); ?></label></td>
        	<td><input type="text" name="cost" id="cost" class="width75" value="" />&nbsp;&nbsp; &nbsp;&nbsp; 
            	<label class="control-label lineblocked autowidth" style="width:auto;">Tax Fees (Ugx):</label> &nbsp;
                <label id="trxfee_display" class="bolded isdecimal width75 lineblocked">0</label>
                <input type="hidden" name="trxfee" id="trxfee" value="" />
                <input type="hidden" name="trxrate" id="trxrate" value="5" />
                <div id="cost_error"></div></td>
        </tr>
        <tr>
            <td><label class="control-label">Net Price (Ugx):</label><span class="pagedescription rightalign lineblocked"><a>after 5% tax fees</a></span></td>
        	<td><label id="netprice_display" class="bolded isdecimal width75 lineblocked">0</label><input type="hidden" name="netprice" id="netprice" value="" /></td>
        </tr>
        <?php if(isAdmin()){ ?>
        <tr>
            <td><label class="control-label"><?php echo $this->translate("product_store_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label></td>
            <td>
            	<?php
                    $values = getAllMerchantStores();
					// debugMessage($values);
                    $dropdown = new Zend_Form_Element_Select('storeid',
                                        array(
                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $values),
                                            'view' => new Zend_View(),
                                            'decorators' => array('ViewHelper'),
                                            'class' => array('span2')
											
                                        )
                    );  
                    $dropdown->setValue($product->getStoreID()); 
                    echo $dropdown->render();
                ?><div id="storeid_error"></div>
            </td>
        </tr>
        <?php } else { ?>
        	<input type="hidden" id="storeid" name="storeid" value="<?php echo $product->getStoreID(); ?>" /><div id="storeid_error"></div>
        <?php } ?>
  </table>
</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>