<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$controller = $request->getControllerName();
	$action = $request->getActionName();
	if($controller == 'profile' && isEmptyString($request->tab)){
		$request->setParam('tab', 'basics'); 
	}
	// debugMessage($product->toArray());
?>
<script>
$(document).ready(function() {
	// override default tab
	<?php if(!isEmptyString($request->tab)){ ?>
		$("#tabs").tabs({ selected:'<?php echo $request->tab; ?>', fx: {opacity: 'toggle'} });	   
	<?php } ?>
	$('#tabs').tabs({
		// the selected tab
		selected: '<?php echo $request->tab; ?>'
	});
	
	<?php if($controller != 'profile'){ ?>
		$("#tabs ul li#tab_summary").removeClass("ui-state-active").removeClass("ui-tabs-selected");
	<?php } ?>
	
	$("#tabs ul#leftnav li a").click(function(e){
		var currentclass = $(this).attr('class');
		var oldclass = '<?php echo $request->tab; ?>';
		if(currentclass != oldclass || currentclass == 'subscription'){
			$(".form-horizontal."+currentclass).html("<a id='loading' class='xhidden' style='text-align:center; display:block; margin-top:75px;'><span style='display:block; margin-bottom:15px; font-weight:bold;'>Loading...</span><img style='margin-left:-10px;' src='<?php echo $this->baseUrl('images/farmisloader.gif'); ?>' /></a>").css({'display':'block'});
			var url = '';
			var controller = '<?php echo $controller; ?>';
			var action = '<?php echo $action; ?>';
			var ismerchant = '<?php echo isMerchant() ? 1 : 0; ?>';
			if(controller == 'product' && action == 'index'){
				var url = "<?php echo $this->baseUrl("product/index/id/".encode($product->getID())."/tab/"); ?>"+currentclass;
			}
			if((controller == 'product' && action == 'view') || currentclass == image || currentclass == download || currentclass == download){
				var url = "<?php echo $this->baseUrl("product/view/id/".encode($product->getID())."/tab/"); ?>"+currentclass;
			}
			if(!isEmptyString(url)){
				location.href = url;  
			}
		}
	});
	
	$("#tabs").tabs().addClass('ui-tabs-vertical ui-helper-clearfix');
	$("#tabs li").removeClass('ui-corner-top').addClass('ui-corner-left');
	
}); 
</script>
<div class="span3 marginleft0" id="left">    
    <div class="well" id="profiletop">
        <div id="profileinfo"> 
			<img id="profileimage" src="<?php echo $product->getMediumPicturePath(); ?>" alt="Update Profile Photo" />
        </div>
    </div>
    <ul id="leftnav" style="width:97%;">
        <li id="tab_general"><a href="#general" class="general">General</a></li>
        <li id="tab_spec"><a href="#spec" class="spec">Specification</a></li>
        <li id="tab_price"><a href="#price" class="price">Price</a></li>
        <li id="tab_image"><a href="#image" class="image">Images</a></li>
        <li id="tab_download"><a href="#download" class="download">Downloads</a></li>
        <li id="tab_account"><a href="#account" class="account">Settings</a></li>   
    </ul>
</div>
