<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>

Dear <?php echo $this->firstname; ?>,<br /><br />

<?php if($this->ismerchantadmin == 1){ ?>
	You have been invited by <b><?php echo $this->inviter; ?></b> to create a Merchant Account on  <?php echo $this->appname; ?>.<br /><br />
	<?php echo $this->appname; ?> is a simple tool to enable you setup a customised platform for your <b><?php echo $this->store; ?></b> store so as to receive online mobile payments<br /><br />
<?php } ?>

In order to get started, you will have to activate your account first by clicking on link below:<br /><br />

<?php echo $this->invitelink; ?><br /><br />

If the page fails to open, copy the activation link and paste it in the address window of the browser.<br />

After activating your account, you should be able to login using the your email address and password.<br /><br />

If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
