<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>
Dear <?php echo $this->firstname; ?>,<br /><br />

We would like to welcome you to <?php echo $this->appname; ?>.<br /><br />

<?php if($this->usertype == 2){ ?>
    To activate your new <?php echo $this->appname; ?> account, click on the activation link below:<br />
    
    <?php echo $this->activationurl; ?><br /><br />
    If the page fails to open, copy the activation link and paste it in the address window of the browser.<br />
    
    After activating your account, you can login using the your email address and the password you provided.<br /><br />
    
    If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />
<?php } ?>

<?php if($this->usertype == 3){ ?>
    However, before you can get started, an administrator will have to approve your merchant account. As soon as this is completed, we will send you a confirmation email so that you can login.<br /><br />
    
    If your account is not approved within 48 hours or need further assistance, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a><br /><br />
<?php } ?>

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
