<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "User Directory";	
	$this->headTitle($title);
	
	$searchnames = '';
	if(!isEmptyString($request->firstname)){
		$searchnames .= $request->firstname;
	}
	if(!isEmptyString($request->lastname)){
		$searchnames .= " ".$request->lastname;
	}
	
	if (!isEmptyString($request->letter)){
		$searchnames .= "Browse By: <b>".strtoupper($request->letter)."</b>";
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.firstname","u.lastname","u.othernames","u.email","u.phone","u.phone2"));
	$paginate->setFilterColumns(array("u.type"));
	// $paginate->setDefaultSortBy("u.datecreated");	
	// $paginate->setDefaultSortOrder("DESC");
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE u.id <> '' ";
	
	if(!isEmptyString($request->firstname)){
		$where_query .= " AND (u.firstname LIKE '%".$request->firstname."%') ";
	}
	if(!isEmptyString($request->lastname)){
		$where_query .= " AND (u.lastname LIKE '%".$request->lastname."%') ";
	}
	if(!isEmptyString($request->othernames)){
		$where_query .= " AND (u.othernames LIKE '%".$request->othernames."%') ";
	}
	
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (u.`firstname` LIKE '".$request->letter."%' OR u.`lastname` LIKE '".$request->letter."%') ";
	}
	
	$listurl = $this->baseUrl('profile/list');
	
	# user status filter
	$status = trim($request->status);
	// debugMessage($status);
	if($status === 0){
		$where_query .= " AND (u.`isactive` = 0) ";
	}
	if($status === 1){
		$where_query .= " AND (u.`isactive` = 1) ";
	}
	if($status == 2){
		$where_query .= " AND (u.`isactive` = 2) ";
	}
	
	$order = trim($request->order);
	$order_query = " ";
	if(isEmptyString($order)){
		$order = 1;
	}
	if($order == 1){
		$order_query = " ORDER BY u.datecreated DESC ";
	}
	if($order == 2){
		$order_query = " ORDER BY u.firstname ASC ";
	}
	if($order == 3){
		$order_query = " ORDER BY u.lastname ASC ";
	}
	if($order == 4){
		$order_query = " ORDER BY u.datecreated ASC ";
	}
	$groupstring = "";
	
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT a.*, u.*, u.email as email, u.phone as phone, u.phone2 as altphone, concat(a.firstname, ' ', a.lastname) as addedby FROM useraccount u left join useraccount a on(u.createdby = a.id) ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY u.id ".$order_query;
	
	// debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
?>
<script>
$(document).ready(function() {
	// set hidden field for the alphabet and submit the form
	$(".alphabet").click(function(){
		var letter = $(this).attr('id');
		// alert(letter);
		$('#letter').val(letter);
		$("#listform").submit();
	});
	
	var dateofregOpts = datepickerOpts;
	datepickerOpts.dateFormat = '<?php echo $config->dateandtime->javascriptmediumformat; ?>';
	// dateofregOpts.maxDate = new Date();
	$("#startdate, #enddate").datepicker(datepickerOpts);
}); 
</script>
<style>		
.alert.alert-success {
	clear:both;
}
.namelabel {
	font-weight:normal;
	font-size:14px;
}
</style>
<div>
	<?php require APPLICATION_PATH."/views/scripts/index/leftcolumn.phtml"; ?>
    <div id="centercolumn">
        <form action="<?php echo $this->baseUrl("profile/listsearch"); ?>" method="get" id="listform" class="form-search">
    	<h1><?php echo $title; ?><?php echo $groupstring; ?></h1>
        <div class="wellcontent" style=" margin-top:-10px;">
            <div class=" blocked clear" style="position:relative; margin-top:25px;">
                <ul id="searchbox">
                    <li>
                        <a style="padding-left:0; padding-right:0; width:100%;">
                            <table id="directorysearchtable" class="table noborder margin0">
                                <tr>
                                    <td style="width:100px; padding-left:2px; padding-right:2px;">
                                    	<label class="control-label">Type:</label>
                                        <?php
                                            $allvalues = getUserType();
											$dropdown = new Zend_Form_Element_Select('u'.HTML_TABLE_COLUMN_SEPARATOR.'type',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $allvalues),
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('type','span2','autofilter')
                                                                )
                                            );  
                                            $dropdown->setValue($request->getParam('u'.HTML_TABLE_COLUMN_SEPARATOR.'type')); 
                                            echo $dropdown->render();
                                        ?>
                                    </td>
                                    <td style="width:85px; padding-left:2px; padding-right:2px;">
                                        <label class="control-label" style="display:block; text-align:left;">Status:</label>
                                            <?php
                                                $allstatus = getUserStatus();
                                                $dropdown = new Zend_Form_Element_Select('status',
                                                                    array(
                                                                        'multiOptions' => array_merge_maintain_keys(array('' => 'All'), $allstatus),
                                                                        'view' => new Zend_View(),
                                                                        'decorators' => array('ViewHelper'),
                                                                        'class' => array('status','span2','autofilter')
                                                                    )
                                                );  
                                                $dropdown->setValue($request->getParam('status')); 
                                                echo $dropdown->render();
                                            ?>
                                    </td>
                                    <td style="width:235px; padding-left:2px; padding-right:2px;">
                                        <label class="control-label" style="display:block; text-align:left;">Ordering:</label>
                                        <?php
                                            $allorders = array('1' => 'Latest First', '4'=>'Earliest First', '2'=>'Alphabetical (First Name)','3'=>'Alphabetical (Last Name)');
                                            $ordersdropdown = new Zend_Form_Element_Select('order',
                                                                array(
                                                                    'multiOptions' => $allorders,
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('gender','span2','autofilter')
                                                                )
                                            );  
                                            $ordersdropdown->setValue($request->getParam('order')); 
                                            echo $ordersdropdown->render();
                                        ?>
                                    </td>
                                    <td style="padding:31px 3px 0 0; text-align:right;">
                                    	<div class="makerelative pull-left">
                                            <input type="hidden" name="advanced" id="advanced" value="<?php echo $request->getParam('advanced'); ?>" />
                                            <input style="width:175px;" name="searchterm" id="searchterm" value="<?php echo $request->searchterm; ?>" type="text" class="input-medium xsearch-query span2 pull-right" placeholder="Search...">
                                            <a style="display:block; float:right; text-align:right; position:absolute; right:5px; top:2px;" href="<?php echo $listurl; ?>" title="Reset list or clear all filters" id="reset" class="removeline close button btn" rel="email">&times;</a>
                                        </div>
                                        <div class="pull-right">
                                        	<button type="submit" id="searchbutton" class="btn" style="padding:6px 10px;"><i class="icon-search"></i></button>
                                        	<input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2"><label class="control-label">Added From: </label>
                                      	<input name="startdate"  id="startdate" type="text"  class="datefield startdate width100 autosearch" value="<?php echo $request->startdate; ?>"  /></td>
                                    <td><label class="control-label">To: </label>
                                    	<input name="enddate" id="enddate" type="text" class="datefield width100 autosearch"  value="<?php echo $request->enddate; ?>" />
                                      	<div class="blocked" id="enddate_error"></div></td>
                                    <td></td>
                                </tr>
                            </table>
                        </a>
                    </li>
                </ul>
          </div>
            <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE))){ ?>
                <div class="alert alert-success clear"><a class="close" data-dismiss="alert">×</a><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
            <?php } ?>
            <?php if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ ?>
                <div class="alert alert-error clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
            <?php } ?>
            <div class="alphabetlist pull-left"><a href="<?php echo $listurl; ?>" title="All Users">All</a>&nbsp;&nbsp;|&nbsp;&nbsp;<?php echo $paginate->getAlphabetString(); ?></div>
            <label style="text-align:left;" class="searchedterm control-label pull-left leftalign"><?php echo $searchnames; ?></label>
            <?php if (!$has_no_data) { ?>
            	<div class="paginatecustom"><?php echo sprintf($this->translate("profile_list_counter"), $paginate->getItemCounterText()); ?></div>
            <?php } ?>
			
			<?php if ($has_no_data) { ?>
            	<div style="clear:both;" class="alert alert-info margin5"><?php echo $this->translate("profile_list_norecords"); ?></div>
            <?php } else { ?>
            	<div class="blocked clear" style="width:auto; max-width:100%; overflow-x:scroll; padding:2px; border:2px solid #3b759a; border-bottom-width:4px; border-right:none;">
                <table class="table list table-striped" style="">
                    <thead>
                        <tr>
                            <td>Actions <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:60px; height:2px;" /></td>
                            <td>Type <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:90px; height:2px;" /></td>
                            <td class="wrapping">First Name <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:50px; height:2px;" /></td>
                            <td class="wrapping">Last Name <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:50px; height:2px;" /></td>
                            <td class="wrapping">Primary Phone</td>
                            <td class="wrapping">Email <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:150px; height:2px;" /></td>
                            <td class="wrapping">Date Activated <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:20px; height:2px;" /></td>
                            <td class="wrapping">Added By <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:80px; height:2px;" /></td>
                            <td class="wrapping">Status <img src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" style="width:60px; height:2px;" /></td>
                        </tr>
                    </thead>
                    <tbody>
                		<?php 				  		
							foreach($result as $line){
								$id = $line['id'];	
								$name = $line['firstname']." ".$line['lastname']." ".$line['othernames'];
								$firstname = $line['firstname'];
								$lastname = $line['lastname'];
								
						?>
                            <tr>
                                <td class="leftalign">
                                	<a class="btn btn-mini lineblocked" href="<?php echo $this->baseUrl('profile/view/id/'.encode($id)); ?>" title="View"><i class="icon-info-sign"></i></a>&nbsp;
                                </td>
                                <td><?php echo getUserType($line['type']); ?></td>
                                <td><?php echo $firstname; ?></td>
                                <td><?php echo $lastname; ?></td>
                                <td><?php echo getShortPhone($line['phone']); ?></td>
                                <td><?php echo $line['email']; ?></td>
                                <td><?php echo isEmptyString($line['activationdate']) ? '--' : date('d/m/Y H:i', strtotime($line['activationdate'])); ?></td>
                                <td><?php echo $line['addedby']; ?></td>
                                <td><?php echo getUserStatus($line['isactive']); ?></td>
                            </tr>
                        <?php } ?>
                	</tbody>
				</table>                    
            	<?php echo $paginate->getPaginationLinks(); ?>  
            <?php } ?>
		</div> 
       </form>         
	</div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
